### ISSUE TITLE
Does not work on annonymous users

### ISSUE THREAD

**Issue by SebaSOFT** [webgilde/advanced-ads-server-lite#2]
The code is very simple to read, congrats on that. But I'm trying to implement using https://github.com/davidjbradshaw/iframe-resizer
and I noticed something, even before the change. Accessing the site anonymously (all my users) gives me a 404 on the Ad URL (its pointing to an "ad group" ad.

How can I debug that "advanced ad" post type can be seen for annonymous users?

Regards

**Comment by webzunft** [comment]
Thanks for reaching out.
I just created a new ad with the "ad group" type and assigned a normal random group to it. I was able to see the ads under the ad URL also when not logged in to the site.
I tested this with a new ad and existing group, but no advanced options. Did you maybe add something else?

**Comment by webzunft** [comment]
Closed due to inactivity. It might be caused by the problem mentioned under [Known Issues](https://wpadvancedads.com/ad-server-wordpress/)
